# Generated by Django 2.0.6 on 2018-07-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('icon', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('withdrawl_fee', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
                ('withdrawl_minimum', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
                ('blockchain_type', models.CharField(choices=[('BTC', 'btc'), ('ETH', 'eth'), ('LTC', 'ltc')], default='BTC', max_length=5)),
                ('decimal_point', models.PositiveIntegerField(default=0)),
                ('is_base', models.BooleanField(default=False)),
                ('is_reusable', models.BooleanField(default=False)),
                ('address_length', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fee', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
                ('trade_minimum', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
                ('base_minimum', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
                ('base', models.ForeignKey(limit_choices_to={'is_base': True}, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='currency.Currency')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='currency.Currency')),
            ],
        ),
    ]
