# Generated by Django 2.0.6 on 2018-08-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('icon', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ticker', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('withdrawal_fee', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
                ('withdrawal_minimum', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
                ('blockchain_type', models.CharField(choices=[('BTC', 'btc'), ('ETH', 'eth'), ('LTC', 'ltc'), ('OMNI', 'omni')], default='BTC', max_length=5)),
                ('decimal_point', models.PositiveIntegerField(default=0)),
                ('is_base', models.BooleanField(default=False)),
                ('is_reusable', models.BooleanField(default=False)),
                ('sync_deposit', models.BooleanField(default=False)),
                ('ERC20', models.BooleanField(default=False)),
                ('abi', models.TextField(default='{}', max_length=200)),
                ('transaction_confirmation_count', models.PositiveIntegerField(default=1)),
                ('contract_address', models.CharField(default='', max_length=200)),
                ('address_length', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fee', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
                ('decimal_point_trade', models.PositiveIntegerField(default=1)),
                ('decimal_point_base', models.PositiveIntegerField(default=1)),
                ('total_minimum', models.DecimalField(decimal_places=5, default=0, max_digits=50)),
                ('tag', models.BooleanField(default=False)),
                ('note', models.CharField(default='', max_length=200)),
                ('req_note', models.CharField(default='', max_length=200)),
                ('base', models.ForeignKey(limit_choices_to={'is_base': True}, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='currency.Currency')),
                ('base_name', models.ForeignKey(default='', limit_choices_to={'is_base': True}, on_delete=django.db.models.deletion.CASCADE, related_name='base_name', to='currency.Currency')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='currency.Currency')),
                ('trade_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trade_name', to='currency.Currency', to_field='name')),
            ],
        ),
    ]
