# Generated by Django 2.0.6 on 2018-08-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='total_minimum',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=50),
        ),
    ]
