# Generated by Django 2.0.6 on 2018-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20180711_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='tag',
            field=models.BooleanField(default=False),
        ),
    ]
