# Generated by Django 2.0.6 on 2018-07-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20180711_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='ERC20',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='abi',
            field=models.TextField(default='{}', max_length=200),
        ),
        migrations.AddField(
            model_name='currency',
            name='contract_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='currency',
            name='transaction_confirmation_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
