# Generated by Django 2.0.6 on 2018-07-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20180725_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='withdrawl_fee',
            new_name='withdrawal_fee',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='withdrawl_minimum',
            new_name='withdrawal_minimum',
        ),
    ]
