# Generated by Django 2.0.6 on 2018-07-31 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20180725_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='base_name',
            field=models.ForeignKey(default='', limit_choices_to={'is_base': True}, on_delete=django.db.models.deletion.CASCADE, related_name='base_name', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='pair',
            name='trade_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trade_name', to='currency.Currency'),
        ),
    ]
